### ISSUE TITLE
Write example

### ISSUE THREAD

**Issue by weepy** [sam-js/sam#5]
it would be nice if this ran out of the box!

**Comment by gunar** [comment]
Agreed.

**Comment by gunar** [comment]
I've put a link to the devtools example for now.

**Comment by weepy** [comment]
It would be great to have a simple example running ! For me at least the dev-tools brings in a whole bunch of complexity which I'm finding hard to dissect. (i.e. which is dev-tools and which is sam).

**Comment by gunar** [comment]
I've pushed the DevTools example, without the DevTools. Surely there is room for improvement, I just wanted to give you something already. Sorry for the delay and please open an Issue if you have any questions. Thank you for your interest :)

**Comment by weepy** [comment]
perfect
